require('dotenv').config();
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
const connectDB = require('../config/database');

const recipes = [
  // ========== FREE ==========
  {
    name: 'Avena proteica para glúteos',
    description: 'Desayuno energético y nutritivo especialmente formulado para potenciar el crecimiento muscular de glúteos. Rico en proteínas, fibra y grasas saludables.',
    imageUrl: 'https://images.pexels.com/photos/1438192/pexels-photo-1438192.jpeg',
    category: 'desayuno',
    accessLevel: 'free',
    prepTime: 2,
    cookTime: 8,
    nutrition: { calories: 520, protein: 20, carbs: 65, fat: 18 },
    tags: ['alto proteico', 'energia', 'gluteos', 'sin lactosa opcional'],
    isFeatured: true,
    ingredients: [
      { name: 'avena en hojuelas', amount: '80', unit: 'g' },
      { name: 'leche o bebida vegetal', amount: '250', unit: 'ml' },
      { name: 'banana madura', amount: '1', unit: 'unidad' },
      { name: 'mantequilla de maní', amount: '20', unit: 'g' },
      { name: 'semillas de chía', amount: '15', unit: 'g' },
      { name: 'cacao en polvo sin azúcar', amount: '10', unit: 'g' },
      { name: 'canela', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Mezclar la avena, la leche, el cacao y la canela en una olla.',
      'Cocinar a fuego medio 5–8 minutos hasta que espese.',
      'Apagar el fuego y agregar la banana triturada, la mantequilla de maní y las semillas de chía.',
      'Servir y, si se desea, añadir un poco más de canela por encima.',
    ],
  },
  {
    name: 'Overnight oats banana y yogur',
    description: 'Desayuno sin cocción listo desde la noche anterior. Cargado de proteína, probióticos y energía de lenta absorción para rendir al máximo.',
    imageUrl: 'https://images.pexels.com/photos/3731474/pexels-photo-3731474.jpeg',
    category: 'desayuno',
    accessLevel: 'free',
    prepTime: 10,
    cookTime: 0,
    nutrition: { calories: 430, protein: 21, carbs: 55, fat: 12 },
    tags: ['sin coccion', 'prep adelantada', 'probioticos', 'alto proteico'],
    isFeatured: false,
    ingredients: [
      { name: 'avena', amount: '60', unit: 'g' },
      { name: 'yogur griego natural', amount: '150', unit: 'g' },
      { name: 'leche o bebida vegetal', amount: '100', unit: 'ml' },
      { name: 'banana en rodajas', amount: '1', unit: 'unidad' },
      { name: 'semillas de linaza molida', amount: '5', unit: 'g' },
      { name: 'miel o stevia', amount: '5', unit: 'g' },
      { name: 'canela', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'En un frasco, mezclar la avena, el yogur, la leche, la linaza y la miel.',
      'Añadir la banana en rodajas y un toque de canela.',
      'Tapar y refrigerar mínimo 4 horas o toda la noche.',
      'Consumir frío al día siguiente.',
    ],
  },
  {
    name: 'Snack piel radiante (yogur, frutos rojos y cacao)',
    description: 'Snack antioxidante que cuida tu piel desde adentro. Combina proteína del yogur griego con los antioxidantes de los frutos rojos y el poder del cacao.',
    imageUrl: 'https://images.pexels.com/photos/1435747/pexels-photo-1435747.jpeg',
    category: 'snack',
    accessLevel: 'free',
    prepTime: 5,
    cookTime: 0,
    nutrition: { calories: 280, protein: 20, carbs: 25, fat: 10 },
    tags: ['antioxidante', 'piel', 'rapido', 'sin coccion'],
    isFeatured: true,
    ingredients: [
      { name: 'yogur griego natural', amount: '200', unit: 'g' },
      { name: 'frutos rojos (arándanos, fresas, moras)', amount: '50', unit: 'g' },
      { name: 'cacao en polvo sin azúcar', amount: '5', unit: 'g' },
      { name: 'semillas de chía', amount: '5', unit: 'g' },
      { name: 'miel o stevia', amount: '5', unit: 'g' },
      { name: 'nueces picadas', amount: '5', unit: 'g' },
    ],
    steps: [
      'Colocar el yogur en un bowl.',
      'Agregar frutos rojos, semillas de chía y nueces.',
      'Espolvorear cacao en polvo.',
      'Endulzar con miel o stevia y mezclar suavemente.',
    ],
  },
  {
    name: 'Batido antiinflamatorio piel radiante',
    description: 'Batido verde cargado de nutrientes antiinflamatorios. Perfecto para reducir la inflamación, hidratar la piel y comenzar el día con energía.',
    imageUrl: 'https://images.pexels.com/photos/5938241/pexels-photo-5938241.jpeg',
    category: 'batido',
    accessLevel: 'free',
    prepTime: 5,
    cookTime: 0,
    nutrition: { calories: 260, protein: 5, carbs: 32, fat: 12 },
    tags: ['antiinflamatorio', 'piel', 'sin gluten', 'vegano', 'verde'],
    isFeatured: true,
    ingredients: [
      { name: 'espinaca fresca', amount: '1', unit: 'taza' },
      { name: 'piña en cubos', amount: '150', unit: 'g' },
      { name: 'aguacate pequeño', amount: '1/2', unit: 'unidad' },
      { name: 'agua de coco', amount: '200', unit: 'ml' },
      { name: 'jengibre fresco', amount: '5', unit: 'g' },
      { name: 'cúrcuma fresca o en polvo', amount: '5', unit: 'g' },
      { name: 'pimienta negra', amount: '1', unit: 'pizca' },
      { name: 'hielo', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Añadir todos los ingredientes a la licuadora.',
      'Licuar hasta obtener una textura cremosa.',
      'Ajustar el espesor con más agua de coco si es necesario.',
      'Servir inmediatamente.',
    ],
  },
  {
    name: 'Shot antiinflamatorio para ojeras y piel',
    description: 'Shot concentrado con cúrcuma, jengibre y naranja. Potente combinación antiinflamatoria para combatir ojeras, mejorar el tono de piel y despertar el sistema inmune.',
    imageUrl: 'https://images.pexels.com/photos/7509521/pexels-photo-7509521.jpeg',
    category: 'bebida',
    accessLevel: 'free',
    prepTime: 5,
    cookTime: 0,
    nutrition: { calories: 45, protein: 1, carbs: 10, fat: 0 },
    tags: ['antiinflamatorio', 'piel', 'ojeras', 'rapido', 'inmunidad'],
    isFeatured: false,
    ingredients: [
      { name: 'naranjas (jugo)', amount: '2', unit: 'unidades' },
      { name: 'jengibre fresco', amount: '5', unit: 'g' },
      { name: 'cúrcuma fresca o en polvo', amount: '5', unit: 'g' },
      { name: 'agua', amount: '50', unit: 'ml' },
      { name: 'pimienta negra', amount: '1', unit: 'pizca' },
    ],
    steps: [
      'Licuar el jugo de naranja con el jengibre, la cúrcuma, el agua y la pimienta.',
      'Colar si se desea una textura más suave.',
      'Servir en vasitos pequeños tipo shot.',
      'Tomar 1 shot al día, preferiblemente en la mañana.',
    ],
  },

  // ========== BASIC ==========
  {
    name: 'Bowl de huevo, aguacate y espinaca',
    description: 'Desayuno completo con proteína de alta calidad, grasas saludables y micronutrientes esenciales. Ideal para mantener la energía y favorecer la definición muscular.',
    imageUrl: 'https://images.pexels.com/photos/5665660/pexels-photo-5665660.jpeg',
    category: 'desayuno',
    accessLevel: 'basic',
    prepTime: 5,
    cookTime: 10,
    nutrition: { calories: 380, protein: 24, carbs: 10, fat: 26 },
    tags: ['alto proteico', 'keto', 'sin gluten', 'grasas saludables'],
    isFeatured: true,
    ingredients: [
      { name: 'huevos', amount: '2', unit: 'unidades' },
      { name: 'clara de huevo', amount: '1', unit: 'unidad' },
      { name: 'aguacate', amount: '1/2', unit: 'unidad' },
      { name: 'espinaca fresca', amount: '1', unit: 'taza' },
      { name: 'tomate cherry', amount: '1/4', unit: 'taza' },
      { name: 'aceite de oliva', amount: '5', unit: 'ml' },
      { name: 'sal y pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Saltear la espinaca con el aceite de oliva en una sartén.',
      'Agregar los huevos y la clara, revolver hasta que estén cocidos.',
      'Servir en un bowl.',
      'Añadir el aguacate en láminas, el tomate cherry y sazonar con sal y pimienta.',
    ],
  },
  {
    name: 'Sándwich de pollo antiinflamatorio',
    description: 'Almuerzo saciante y antiinflamatorio con proteína magra de pollo, aguacate y mostaza Dijon. Perfecto para recuperar después del entrenamiento.',
    imageUrl: 'https://images.pexels.com/photos/4109138/pexels-photo-4109138.jpeg',
    category: 'almuerzo',
    accessLevel: 'basic',
    prepTime: 10,
    cookTime: 0,
    nutrition: { calories: 430, protein: 32, carbs: 35, fat: 18 },
    tags: ['alto proteico', 'post entreno', 'antiinflamatorio'],
    isFeatured: false,
    ingredients: [
      { name: 'pan integral o masa madre', amount: '2', unit: 'rebanadas' },
      { name: 'pechuga de pollo cocida y desmechada', amount: '100', unit: 'g' },
      { name: 'aguacate en láminas', amount: '1/2', unit: 'unidad' },
      { name: 'lechuga', amount: '2', unit: 'hojas' },
      { name: 'tomate', amount: '2', unit: 'rodajas' },
      { name: 'mayonesa ligera', amount: '10', unit: 'g' },
      { name: 'mostaza Dijon', amount: '5', unit: 'g' },
      { name: 'aceite de oliva', amount: '5', unit: 'ml' },
      { name: 'limón (jugo)', amount: 'al gusto', unit: '' },
      { name: 'sal y pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Mezclar la mayonesa con la mostaza y un poco de limón.',
      'Untar la mezcla en las rebanadas de pan.',
      'Armar el sándwich con lechuga, pollo, tomate y aguacate.',
      'Rociar con aceite de oliva, sal y pimienta al gusto.',
    ],
  },
  {
    name: 'Tofu o pollo salteado alto en proteína',
    description: 'Cena ligera y versátil, apta para veganas y omnívoras. Alta en proteína, bajo en carbohidratos y lista en menos de 20 minutos.',
    imageUrl: 'https://images.pexels.com/photos/4106480/pexels-photo-4106480.jpeg',
    category: 'cena',
    accessLevel: 'basic',
    prepTime: 5,
    cookTime: 10,
    nutrition: { calories: 350, protein: 28, carbs: 18, fat: 16 },
    tags: ['alto proteico', 'bajo carbos', 'sin gluten', 'rapido'],
    isFeatured: false,
    ingredients: [
      { name: 'tofu firme o pechuga de pollo en cubos', amount: '150', unit: 'g' },
      { name: 'mix de verduras (brócoli, zanahoria, pimentón)', amount: '1', unit: 'taza' },
      { name: 'salsa de soya baja en sodio', amount: '10', unit: 'ml' },
      { name: 'aceite de oliva o coco', amount: '5', unit: 'ml' },
      { name: 'ajo y jengibre', amount: 'al gusto', unit: '' },
      { name: 'pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Calentar el aceite en una sartén.',
      'Saltear ajo y jengibre, luego añadir el tofu o pollo y dorar.',
      'Agregar las verduras y la salsa de soya, cocinar 5–7 minutos.',
      'Servir solo o con 1/2 taza de arroz integral si se desea.',
    ],
  },
  {
    name: 'Yogur griego con mantequilla de maní y frutos rojos',
    description: 'Snack proteico irresistible que combina la cremosidad del yogur griego con el sabor intenso del maní y la frescura de los frutos rojos. Listo en 5 minutos.',
    imageUrl: 'https://images.pexels.com/photos/1431305/pexels-photo-1431305.jpeg',
    category: 'snack',
    accessLevel: 'basic',
    prepTime: 5,
    cookTime: 0,
    nutrition: { calories: 320, protein: 22, carbs: 20, fat: 16 },
    tags: ['alto proteico', 'rapido', 'antioxidante', 'sin coccion'],
    isFeatured: false,
    ingredients: [
      { name: 'yogur griego natural', amount: '200', unit: 'g' },
      { name: 'mantequilla de maní', amount: '15', unit: 'g' },
      { name: 'frutos rojos', amount: '50', unit: 'g' },
      { name: 'chocolate 70% derretido o en trocitos', amount: '5', unit: 'g' },
    ],
    steps: [
      'Servir el yogur en un bowl.',
      'Añadir la mantequilla de maní y mezclar ligeramente.',
      'Agregar los frutos rojos.',
      'Decorar con el chocolate por encima.',
    ],
  },

  // ========== FREE (nuevas) ==========
  {
    name: 'Tortilla proteica de huevo y espinaca',
    description: 'Tortilla cargada de proteína y hierro, lista en minutos. Perfecta para un desayuno completo que te mantiene activa y con energía toda la mañana.',
    imageUrl: 'https://images.pexels.com/photos/3296278/pexels-photo-3296278.jpeg',
    category: 'desayuno',
    accessLevel: 'free',
    prepTime: 3,
    cookTime: 8,
    nutrition: { calories: 380, protein: 30, carbs: 25, fat: 17 },
    tags: ['alto proteico', 'hierro', 'rapido', 'sin lactosa opcional'],
    isFeatured: false,
    ingredients: [
      { name: 'huevos enteros', amount: '2', unit: 'unidades' },
      { name: 'claras de huevo', amount: '2', unit: 'unidades' },
      { name: 'espinaca picada', amount: '1', unit: 'taza' },
      { name: 'queso fresco bajo en grasa', amount: '30', unit: 'g' },
      { name: 'pan integral', amount: '1', unit: 'rebanada' },
      { name: 'aceite de oliva', amount: '5', unit: 'ml' },
      { name: 'sal y pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Batir huevos y claras con sal y pimienta.',
      'Saltear la espinaca en aceite de oliva.',
      'Añadir la mezcla de huevo y cocinar tipo tortilla.',
      'Servir con el queso por encima y el pan integral al lado.',
    ],
  },
  {
    name: 'Overnight oats para glúteos',
    description: 'Versión potenciada de overnight oats con proteína y mantequilla de maní, diseñada para maximizar el crecimiento de glúteos durante la noche y el día.',
    imageUrl: 'https://images.pexels.com/photos/3731520/pexels-photo-3731520.jpeg',
    category: 'desayuno',
    accessLevel: 'free',
    prepTime: 10,
    cookTime: 0,
    nutrition: { calories: 520, protein: 28, carbs: 60, fat: 18 },
    tags: ['alto proteico', 'gluteos', 'prep adelantada', 'sin coccion'],
    isFeatured: true,
    ingredients: [
      { name: 'avena', amount: '70', unit: 'g' },
      { name: 'leche o bebida vegetal', amount: '200', unit: 'ml' },
      { name: 'proteína en polvo (opcional)', amount: '20', unit: 'g' },
      { name: 'banana en rodajas', amount: '1', unit: 'unidad' },
      { name: 'mantequilla de maní', amount: '10', unit: 'g' },
      { name: 'semillas de chía', amount: '10', unit: 'g' },
      { name: 'canela', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Mezclar avena, leche y proteína en polvo en un frasco.',
      'Añadir chía y canela, mezclar bien.',
      'Colocar la banana y la mantequilla de maní encima.',
      'Refrigerar mínimo 4 horas o toda la noche.',
    ],
  },

  // ========== BASIC (nuevas) ==========
  {
    name: 'Bowl de pollo, camote y brócoli',
    description: 'Bowl completo con carbohidratos de calidad, proteína magra y vegetales al vapor. Ideal para el almuerzo post entrenamiento y para nutrir glúteos y piernas.',
    imageUrl: 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg',
    category: 'almuerzo',
    accessLevel: 'basic',
    prepTime: 10,
    cookTime: 30,
    nutrition: { calories: 520, protein: 35, carbs: 55, fat: 14 },
    tags: ['alto proteico', 'post entreno', 'sin gluten', 'gluteos'],
    isFeatured: true,
    ingredients: [
      { name: 'pechuga de pollo a la plancha', amount: '120', unit: 'g' },
      { name: 'camote (batata) asado en cubos', amount: '150', unit: 'g' },
      { name: 'brócoli al vapor', amount: '1', unit: 'taza' },
      { name: 'aceite de oliva', amount: '10', unit: 'ml' },
      { name: 'sal, pimienta, pimentón dulce y ajo en polvo', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Asar el camote en cubos con aceite de oliva y especias 25–30 minutos.',
      'Cocinar el pollo a la plancha y cortarlo en tiras.',
      'Cocinar el brócoli al vapor.',
      'Armar el bowl con camote, brócoli y pollo, y ajustar sal y pimienta.',
    ],
  },
  {
    name: 'Ensalada de lentejas para pierna fuerte',
    description: 'Ensalada rica en proteína vegetal, fibra y hierro. Las lentejas combinadas con arroz integral ofrecen una proteína completa ideal para el desarrollo muscular de piernas.',
    imageUrl: 'https://images.pexels.com/photos/5938241/pexels-photo-5938241.jpeg',
    category: 'almuerzo',
    accessLevel: 'basic',
    prepTime: 10,
    cookTime: 0,
    nutrition: { calories: 490, protein: 22, carbs: 75, fat: 12 },
    tags: ['vegano', 'fibra', 'hierro', 'piernas', 'sin gluten'],
    isFeatured: false,
    ingredients: [
      { name: 'lentejas cocidas', amount: '120', unit: 'g' },
      { name: 'arroz integral cocido', amount: '1/2', unit: 'taza' },
      { name: 'pepino en cubos', amount: '1/2', unit: 'taza' },
      { name: 'pimentón en cubos', amount: '1/2', unit: 'taza' },
      { name: 'cebolla morada', amount: '1/4', unit: 'unidad' },
      { name: 'aceite de oliva', amount: '10', unit: 'ml' },
      { name: 'limón (jugo)', amount: '1/2', unit: 'unidad' },
      { name: 'sal, comino y pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Mezclar las lentejas con el arroz integral en un bowl.',
      'Agregar pepino, pimentón y cebolla.',
      'Aliñar con aceite de oliva, limón, sal, comino y pimienta.',
      'Servir fría o a temperatura ambiente.',
    ],
  },

  // ========== PREMIUM ==========
  {
    name: 'Ensalada power de salmón y quinoa',
    description: 'Almuerzo premium con omega-3 del salmón, proteína completa de la quinoa y antioxidantes de las hojas verdes. Una combinación perfecta para piel, músculo y energía.',
    imageUrl: 'https://images.pexels.com/photos/3296273/pexels-photo-3296273.jpeg',
    category: 'almuerzo',
    accessLevel: 'premium',
    prepTime: 10,
    cookTime: 10,
    nutrition: { calories: 520, protein: 34, carbs: 35, fat: 24 },
    tags: ['omega 3', 'alto proteico', 'antiinflamatorio', 'piel', 'sin gluten'],
    isFeatured: true,
    ingredients: [
      { name: 'salmón a la plancha', amount: '100', unit: 'g' },
      { name: 'quinoa cocida', amount: '60', unit: 'g' },
      { name: 'espinaca o mezcla de hojas verdes', amount: '1', unit: 'taza' },
      { name: 'pepino en rodajas', amount: '1/4', unit: 'unidad' },
      { name: 'zanahoria rallada', amount: '1/4', unit: 'taza' },
      { name: 'semillas de girasol', amount: '1', unit: 'cda' },
      { name: 'aceite de oliva', amount: '10', unit: 'ml' },
      { name: 'limón (jugo)', amount: '1/2', unit: 'unidad' },
      { name: 'sal y pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Colocar la mezcla de hojas verdes en un plato.',
      'Añadir la quinoa cocida, el pepino y la zanahoria.',
      'Ubicar el salmón desmenuzado encima.',
      'Aliñar con aceite de oliva, limón, sal y pimienta, y finalizar con las semillas de girasol.',
    ],
  },
  {
    name: 'Bowl de garbanzos y verduras para piel y músculo',
    description: 'Bowl vegano completo con proteína vegetal, fibra y antiinflamatorios naturales. Ideal para quienes buscan alimentarse saludablemente sin carne.',
    imageUrl: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg',
    category: 'almuerzo',
    accessLevel: 'premium',
    prepTime: 10,
    cookTime: 5,
    nutrition: { calories: 480, protein: 18, carbs: 55, fat: 18 },
    tags: ['vegano', 'fibra', 'antiinflamatorio', 'piel', 'sin gluten'],
    isFeatured: false,
    ingredients: [
      { name: 'garbanzos cocidos', amount: '120', unit: 'g' },
      { name: 'arroz integral cocido', amount: '1/2', unit: 'taza' },
      { name: 'brócoli al vapor', amount: '1', unit: 'taza' },
      { name: 'zanahoria rallada', amount: '1/4', unit: 'taza' },
      { name: 'aguacate', amount: '1/4', unit: 'unidad' },
      { name: 'aceite de oliva', amount: '10', unit: 'ml' },
      { name: 'limón (jugo)', amount: 'al gusto', unit: '' },
      { name: 'cúrcuma y pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'En un bowl, colocar el arroz integral como base.',
      'Añadir los garbanzos, el brócoli y la zanahoria.',
      'Agregar el aguacate en láminas.',
      'Aliñar con aceite de oliva, limón, cúrcuma, pimienta y mezclar ligeramente.',
    ],
  },
  {
    name: 'Cena ligera de clara de huevo y verduras',
    description: 'Cena baja en calorías y altísima en proteína. Perfecta para después de las 7pm, sin carbohidratos pesados y con máximo aporte nutricional para la recuperación nocturna.',
    imageUrl: 'https://images.pexels.com/photos/3731471/pexels-photo-3731471.jpeg',
    category: 'cena',
    accessLevel: 'premium',
    prepTime: 5,
    cookTime: 8,
    nutrition: { calories: 260, protein: 28, carbs: 6, fat: 12 },
    tags: ['alto proteico', 'bajo calorias', 'sin gluten', 'nocturno'],
    isFeatured: true,
    ingredients: [
      { name: 'claras de huevo', amount: '4', unit: 'unidades' },
      { name: 'huevo entero', amount: '1', unit: 'unidad' },
      { name: 'mix de verduras (espinaca, champiñones, pimentón)', amount: '1', unit: 'taza' },
      { name: 'aceite de oliva', amount: '5', unit: 'ml' },
      { name: 'sal, pimienta y orégano', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Saltear las verduras en aceite de oliva hasta que estén blandas.',
      'Batir las claras con el huevo entero, sal, pimienta y orégano.',
      'Verter la mezcla sobre las verduras y cocinar a fuego medio hasta que cuaje.',
      'Servir caliente.',
    ],
  },
  {
    name: 'Pasta integral con carne magra',
    description: 'Plato clásico reformulado con pasta integral y carne magra. Alto en proteína y carbohidratos complejos para recargar energía y apoyar la construcción muscular.',
    imageUrl: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg',
    category: 'almuerzo',
    accessLevel: 'premium',
    prepTime: 5,
    cookTime: 20,
    nutrition: { calories: 550, protein: 35, carbs: 65, fat: 14 },
    tags: ['alto proteico', 'carbohidratos complejos', 'post entreno', 'energia'],
    isFeatured: false,
    ingredients: [
      { name: 'pasta integral en crudo', amount: '70', unit: 'g' },
      { name: 'carne molida magra (res o pavo)', amount: '100', unit: 'g' },
      { name: 'salsa de tomate natural', amount: '1/2', unit: 'taza' },
      { name: 'espinaca', amount: '1/2', unit: 'taza' },
      { name: 'aceite de oliva', amount: '5', unit: 'ml' },
      { name: 'ajo, sal, pimienta y orégano', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Cocinar la pasta integral según instrucciones del empaque.',
      'Saltear ajo en aceite de oliva, añadir la carne y dorar.',
      'Agregar salsa de tomate, espinaca y especias, cocinar 5 minutos.',
      'Mezclar la pasta con la salsa y servir.',
    ],
  },
  // ========== SNACKS PRE/POST ENTRENO ==========
  {
    name: 'Banana con mantequilla de maní (pre entreno)',
    description: 'Snack rápido y energético ideal 30–45 minutos antes de entrenar glúteos o piernas. Carbohidratos de rápida absorción + grasas saludables para rendimiento máximo.',
    imageUrl: 'https://images.pexels.com/photos/4198014/pexels-photo-4198014.jpeg',
    category: 'snack',
    accessLevel: 'free',
    prepTime: 2,
    cookTime: 0,
    nutrition: { calories: 210, protein: 5, carbs: 30, fat: 8 },
    tags: ['pre entreno', 'rapido', 'energia', 'gluteos', 'sin coccion'],
    isFeatured: false,
    ingredients: [
      { name: 'banana mediana', amount: '1', unit: 'unidad' },
      { name: 'mantequilla de maní natural', amount: '15', unit: 'g' },
    ],
    steps: [
      'Pelar la banana.',
      'Untar la mantequilla de maní por encima o cortar la banana en rodajas y agregar la mantequilla.',
      'Consumir 30–45 minutos antes de entrenar glúteos/piernas.',
    ],
  },
  {
    name: 'Yogur griego con fruta (pre entreno)',
    description: 'Pre entreno ligero con proteína y azúcares naturales de la fruta. Digestión fácil y energía sostenida para un entrenamiento de calidad.',
    imageUrl: 'https://images.pexels.com/photos/4144202/pexels-photo-4144202.jpeg',
    category: 'snack',
    accessLevel: 'free',
    prepTime: 5,
    cookTime: 0,
    nutrition: { calories: 190, protein: 15, carbs: 22, fat: 4 },
    tags: ['pre entreno', 'proteico', 'rapido', 'sin coccion', 'probioticos'],
    isFeatured: false,
    ingredients: [
      { name: 'yogur griego natural alto en proteína', amount: '150', unit: 'g' },
      { name: 'manzana o frutos rojos', amount: '1/2', unit: 'taza' },
      { name: 'miel o stevia', amount: '5', unit: 'g' },
    ],
    steps: [
      'Colocar el yogur en un bowl.',
      'Agregar la fruta en trozos.',
      'Endulzar con miel o stevia.',
      'Consumir 45–60 minutos antes del entrenamiento.',
    ],
  },
  {
    name: 'Tostada integral con huevo (pre entreno)',
    description: 'Pre entreno completo con carbohidratos de absorción lenta y proteína de calidad. Simple, rápido y efectivo para mantener la energía durante toda la sesión.',
    imageUrl: 'https://images.pexels.com/photos/4109131/pexels-photo-4109131.jpeg',
    category: 'snack',
    accessLevel: 'basic',
    prepTime: 2,
    cookTime: 5,
    nutrition: { calories: 220, protein: 11, carbs: 20, fat: 10 },
    tags: ['pre entreno', 'proteico', 'rapido', 'energia'],
    isFeatured: false,
    ingredients: [
      { name: 'pan integral', amount: '1', unit: 'rebanada' },
      { name: 'huevo', amount: '1', unit: 'unidad' },
      { name: 'aceite de oliva', amount: '5', unit: 'ml' },
      { name: 'sal y pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Tostar el pan integral.',
      'En una sartén con un poco de aceite, cocinar el huevo (frito, revuelto o a la plancha).',
      'Colocar el huevo sobre la tostada y sazonar con sal y pimienta.',
      'Consumir 45–60 minutos antes de entrenar.',
    ],
  },
  {
    name: 'Arroz con atún rápido (post entreno)',
    description: 'Clásico post entreno con la proporción ideal de carbohidratos y proteína para la recuperación muscular. Listo en 5 minutos.',
    imageUrl: 'https://images.pexels.com/photos/6546027/pexels-photo-6546027.jpeg',
    category: 'snack',
    accessLevel: 'basic',
    prepTime: 5,
    cookTime: 0,
    nutrition: { calories: 330, protein: 24, carbs: 38, fat: 8 },
    tags: ['post entreno', 'rapido', 'alto proteico', 'recuperacion', 'sin gluten'],
    isFeatured: true,
    ingredients: [
      { name: 'arroz blanco cocido', amount: '80', unit: 'g' },
      { name: 'atún en agua escurrido', amount: '80', unit: 'g' },
      { name: 'aceite de oliva', amount: '5', unit: 'ml' },
      { name: 'sal, pimienta y limón', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Mezclar el arroz cocido con el atún en un bowl.',
      'Añadir aceite de oliva, sal, pimienta y un poco de limón.',
      'Revolver bien y servir.',
      'Consumir dentro de los 60 minutos posteriores al entreno.',
    ],
  },
  {
    name: 'Wrap de pollo y aguacate (post entreno)',
    description: 'Post entreno premium con proteína magra, grasas antiinflamatorias del aguacate y carbohidratos de la tortilla integral. Recuperación y sabor en un solo wrap.',
    imageUrl: 'https://images.pexels.com/photos/4109139/pexels-photo-4109139.jpeg',
    category: 'snack',
    accessLevel: 'premium',
    prepTime: 8,
    cookTime: 0,
    nutrition: { calories: 340, protein: 27, carbs: 28, fat: 12 },
    tags: ['post entreno', 'alto proteico', 'recuperacion', 'antiinflamatorio'],
    isFeatured: true,
    ingredients: [
      { name: 'tortilla integral mediana', amount: '1', unit: 'unidad' },
      { name: 'pechuga de pollo cocida y desmechada', amount: '80', unit: 'g' },
      { name: 'aguacate en láminas', amount: '1/4', unit: 'unidad' },
      { name: 'yogur griego natural', amount: '20', unit: 'g' },
      { name: 'sal, pimienta y limón', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Mezclar el pollo desmechado con el yogur griego, sal, pimienta y limón.',
      'Colocar la mezcla en la tortilla integral.',
      'Añadir las láminas de aguacate.',
      'Enrollar el wrap y cortar por la mitad.',
    ],
  },
  {
    name: 'Shake de proteína con avena (post entreno)',
    description: 'Batido post entreno por excelencia. Proteína de rápida absorción + carbohidratos de la avena y la banana para reponer glucógeno y acelerar la recuperación muscular.',
    imageUrl: 'https://images.pexels.com/photos/1438084/pexels-photo-1438084.jpeg',
    category: 'batido',
    accessLevel: 'premium',
    prepTime: 5,
    cookTime: 0,
    nutrition: { calories: 330, protein: 25, carbs: 38, fat: 6 },
    tags: ['post entreno', 'alto proteico', 'recuperacion', 'batido', 'energia'],
    isFeatured: true,
    ingredients: [
      { name: 'leche o bebida vegetal', amount: '200', unit: 'ml' },
      { name: 'proteína en polvo', amount: '1', unit: 'scoop (20–25g proteína)' },
      { name: 'avena', amount: '30', unit: 'g' },
      { name: 'banana', amount: '1/2', unit: 'unidad' },
      { name: 'hielo', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Agregar a la licuadora la leche, la proteína en polvo, la avena y la banana.',
      'Añadir hielo al gusto.',
      'Licuar hasta que quede una textura cremosa.',
      'Tomar inmediatamente después de entrenar.',
    ],
  },

  // ========== NUEVAS RECETAS ==========
  {
    name: 'Omelette ligero de claras y vegetales',
    description: 'Omelette bajo en calorías y alto en proteína, relleno de vegetales salteados. Ideal para empezar el día con energía sin pesadez.',
    imageUrl: 'https://images.pexels.com/photos/3731471/pexels-photo-3731471.jpeg',
    category: 'desayuno',
    accessLevel: 'free',
    prepTime: 5,
    cookTime: 8,
    nutrition: { calories: 220, protein: 24, carbs: 6, fat: 10 },
    tags: ['alto proteico', 'bajo carbos', 'keto', 'sin gluten', 'rapido'],
    isFeatured: false,
    ingredients: [
      { name: 'claras de huevo', amount: '3', unit: 'unidades' },
      { name: 'huevo entero', amount: '1', unit: 'unidad' },
      { name: 'espinaca picada', amount: '1/2', unit: 'taza' },
      { name: 'champiñones en láminas', amount: '1/4', unit: 'taza' },
      { name: 'cebolla picada', amount: '1/4', unit: 'unidad' },
      { name: 'aceite de oliva', amount: '5', unit: 'ml' },
      { name: 'sal y pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Saltear cebolla y champiñones con el aceite de oliva.',
      'Añadir la espinaca y cocinar 1–2 minutos.',
      'Batir claras y huevo con sal y pimienta, verter sobre las verduras.',
      'Cocinar a fuego medio hasta que cuaje, doblar y servir.',
    ],
  },
  {
    name: 'Avena fit alta en proteína',
    description: 'Avena cremosa enriquecida con yogur griego para duplicar el aporte proteico. Perfecta para quienes cuidan las calorías sin sacrificar energía ni sabor.',
    imageUrl: 'https://images.pexels.com/photos/3731474/pexels-photo-3731474.jpeg',
    category: 'desayuno',
    accessLevel: 'free',
    prepTime: 2,
    cookTime: 7,
    nutrition: { calories: 260, protein: 18, carbs: 38, fat: 5 },
    tags: ['alto proteico', 'bajo calorias', 'probioticos', 'energia'],
    isFeatured: false,
    ingredients: [
      { name: 'avena', amount: '40', unit: 'g' },
      { name: 'leche o bebida vegetal baja en calorías', amount: '200', unit: 'ml' },
      { name: 'yogur griego light', amount: '100', unit: 'g' },
      { name: 'banana en rodajas', amount: '1/2', unit: 'unidad' },
      { name: 'canela', amount: 'al gusto', unit: '' },
      { name: 'stevia', amount: 'opcional', unit: '' },
    ],
    steps: [
      'Cocinar la avena con la leche hasta que espese.',
      'Retirar del fuego y dejar entibiar.',
      'Agregar el yogur griego y mezclar.',
      'Decorar con la banana y canela; endulzar con stevia si se desea.',
    ],
  },
  {
    name: 'Ensalada ligera de pollo',
    description: 'Ensalada fresca y saciante con proteína magra de pollo y vegetales crujientes. Perfecta para el almuerzo cuando el objetivo es definición y mantenerse liviana.',
    imageUrl: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg',
    category: 'almuerzo',
    accessLevel: 'free',
    prepTime: 10,
    cookTime: 0,
    nutrition: { calories: 320, protein: 30, carbs: 10, fat: 18 },
    tags: ['alto proteico', 'bajo carbos', 'sin gluten', 'keto', 'definicion'],
    isFeatured: false,
    ingredients: [
      { name: 'pechuga de pollo a la plancha en tiras', amount: '100', unit: 'g' },
      { name: 'mezcla de lechugas', amount: '2', unit: 'tazas' },
      { name: 'pepino en rodajas', amount: '1/2', unit: 'taza' },
      { name: 'tomate cherry', amount: '1/2', unit: 'taza' },
      { name: 'cebolla morada', amount: '1/4', unit: 'unidad' },
      { name: 'aceite de oliva', amount: '10', unit: 'ml' },
      { name: 'limón (jugo)', amount: '1/2', unit: 'unidad' },
      { name: 'sal y pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Colocar las lechugas en un bowl.',
      'Añadir pepino, tomate y cebolla.',
      'Agregar el pollo en tiras.',
      'Aliñar con aceite de oliva, limón, sal y pimienta, y mezclar.',
    ],
  },
  {
    name: 'Bowl vegetariano de judías pintas y arroz',
    description: 'Bowl vegano con proteína completa al combinar legumbres y cereal. Rico en fibra, hierro y carbohidratos complejos para sostener la energía todo el día.',
    imageUrl: 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg',
    category: 'almuerzo',
    accessLevel: 'basic',
    prepTime: 8,
    cookTime: 5,
    nutrition: { calories: 330, protein: 14, carbs: 52, fat: 7 },
    tags: ['vegano', 'fibra', 'hierro', 'sin gluten', 'proteina vegetal'],
    isFeatured: false,
    ingredients: [
      { name: 'judías pintas cocidas', amount: '80', unit: 'g' },
      { name: 'arroz integral cocido', amount: '40', unit: 'g' },
      { name: 'pimentón en cubos', amount: '1/4', unit: 'taza' },
      { name: 'zanahoria rallada', amount: '1/4', unit: 'taza' },
      { name: 'tomate picado', amount: '1/4', unit: 'taza' },
      { name: 'aceite de oliva', amount: '5', unit: 'ml' },
      { name: 'sal, pimentón dulce y comino', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Mezclar las judías con el arroz en un bowl.',
      'Añadir pimentón, zanahoria y tomate.',
      'Aliñar con aceite de oliva, sal, pimentón dulce y comino.',
      'Mezclar y servir tibio.',
    ],
  },
  {
    name: 'Tacos de lechuga con pavo',
    description: 'Cena ligera y divertida sin carbohidratos pesados. La lechuga reemplaza la tortilla para una opción baja en calorías con toda la proteína del pavo.',
    imageUrl: 'https://images.pexels.com/photos/6546027/pexels-photo-6546027.jpeg',
    category: 'cena',
    accessLevel: 'basic',
    prepTime: 5,
    cookTime: 10,
    nutrition: { calories: 260, protein: 28, carbs: 8, fat: 11 },
    tags: ['alto proteico', 'bajo carbos', 'sin gluten', 'keto', 'rapido'],
    isFeatured: false,
    ingredients: [
      { name: 'pechuga de pavo molida o picada', amount: '100', unit: 'g' },
      { name: 'hojas grandes de lechuga', amount: '4', unit: 'unidades' },
      { name: 'cebolla picada', amount: '1/4', unit: 'taza' },
      { name: 'tomate picado', amount: '1/4', unit: 'taza' },
      { name: 'pimentón', amount: '1/4', unit: 'taza' },
      { name: 'aceite de oliva', amount: '5', unit: 'ml' },
      { name: 'sal, pimienta, comino y paprika', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Saltear la cebolla y el pimentón con aceite de oliva.',
      'Añadir el pavo y cocinar hasta que esté dorado.',
      'Sazonar con sal, pimienta, comino y paprika.',
      'Rellenar las hojas de lechuga con la mezcla de pavo y el tomate picado.',
    ],
  },
  {
    name: 'Ensalada de garbanzos rápida',
    description: 'Cena fresca y digestiva con proteína vegetal y vegetales crudos. Lista en 5 minutos, sin cocción, ideal para noches en que quieres algo ligero pero nutritivo.',
    imageUrl: 'https://images.pexels.com/photos/1435895/pexels-photo-1435895.jpeg',
    category: 'cena',
    accessLevel: 'premium',
    prepTime: 5,
    cookTime: 0,
    nutrition: { calories: 280, protein: 11, carbs: 32, fat: 11 },
    tags: ['vegano', 'sin coccion', 'fibra', 'sin gluten', 'rapido'],
    isFeatured: false,
    ingredients: [
      { name: 'garbanzos cocidos', amount: '100', unit: 'g' },
      { name: 'pepino en cubos', amount: '1/2', unit: 'taza' },
      { name: 'tomate en cubos', amount: '1/2', unit: 'taza' },
      { name: 'cebolla morada', amount: '1/4', unit: 'unidad' },
      { name: 'aceite de oliva', amount: '10', unit: 'ml' },
      { name: 'limón (jugo)', amount: '1/2', unit: 'unidad' },
      { name: 'sal, pimienta y perejil picado', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'En un bowl, mezclar garbanzos, pepino, tomate y cebolla.',
      'Agregar aceite de oliva, limón, sal y pimienta.',
      'Añadir perejil picado y mezclar bien.',
      'Servir fría.',
    ],
  },
  {
    name: 'Snack de zanahoria y hummus',
    description: 'Snack crujiente y nutritivo con la combinación perfecta de fibra de la zanahoria y proteína vegetal del hummus. Sin culpa y sin cocción.',
    imageUrl: 'https://images.pexels.com/photos/3730951/pexels-photo-3730951.jpeg',
    category: 'snack',
    accessLevel: 'free',
    prepTime: 3,
    cookTime: 0,
    nutrition: { calories: 140, protein: 4, carbs: 14, fat: 7 },
    tags: ['vegano', 'sin coccion', 'fibra', 'rapido', 'sin gluten'],
    isFeatured: false,
    ingredients: [
      { name: 'zanahoria en bastones', amount: '80', unit: 'g' },
      { name: 'hummus clásico', amount: '40', unit: 'g' },
    ],
    steps: [
      'Lavar y cortar la zanahoria en bastones.',
      'Servir el hummus en un recipiente pequeño.',
      'Acompañar los bastones de zanahoria con el hummus como dip.',
    ],
  },
  {
    name: 'Yogur griego con semillas',
    description: 'Snack rico en proteína, omega-3 y fibra soluble. Las semillas de chía y linaza potencian la saciedad y el equilibrio hormonal, perfectas para el control del peso.',
    imageUrl: 'https://images.pexels.com/photos/4144224/pexels-photo-4144224.jpeg',
    category: 'snack',
    accessLevel: 'basic',
    prepTime: 3,
    cookTime: 0,
    nutrition: { calories: 150, protein: 15, carbs: 7, fat: 6 },
    tags: ['alto proteico', 'omega 3', 'fibra', 'sin coccion', 'probioticos'],
    isFeatured: false,
    ingredients: [
      { name: 'yogur griego light', amount: '150', unit: 'g' },
      { name: 'semillas de chía', amount: '5', unit: 'g' },
      { name: 'semillas de linaza molida', amount: '5', unit: 'g' },
      { name: 'stevia o gotas de vainilla', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Colocar el yogur en un bowl.',
      'Añadir chía y linaza por encima.',
      'Endulzar con stevia o saborizar con vainilla.',
      'Mezclar y servir frío.',
    ],
  },
  {
    name: 'Batido verde quema grasa',
    description: 'Batido detox bajo en calorías con espinaca, pepino y manzana verde. Aliado de la definición muscular, la hidratación y la reducción de inflamación.',
    imageUrl: 'https://images.pexels.com/photos/5938241/pexels-photo-5938241.jpeg',
    category: 'batido',
    accessLevel: 'premium',
    prepTime: 5,
    cookTime: 0,
    nutrition: { calories: 90, protein: 2, carbs: 20, fat: 0 },
    tags: ['detox', 'bajo calorias', 'vegano', 'sin gluten', 'definicion'],
    isFeatured: false,
    ingredients: [
      { name: 'espinaca', amount: '1', unit: 'taza' },
      { name: 'pepino', amount: '1/2', unit: 'unidad' },
      { name: 'manzana verde', amount: '1/2', unit: 'unidad' },
      { name: 'limón (jugo)', amount: '1/2', unit: 'unidad' },
      { name: 'agua fría', amount: '200', unit: 'ml' },
      { name: 'hielo', amount: 'al gusto', unit: '' },
      { name: 'stevia', amount: 'opcional', unit: '' },
    ],
    steps: [
      'Añadir todos los ingredientes a la licuadora.',
      'Licuar hasta obtener una mezcla homogénea.',
      'Ajustar dulzor con stevia si se desea.',
      'Servir inmediatamente.',
    ],
  },

  {
    name: 'Desayuno – Omelette ligero + tostada integral',
    description: 'Desayuno completo con proteína de huevo, vegetales salteados y carbohidratos de la tostada integral. Energía y saciedad equilibradas para comenzar el día.',
    imageUrl: 'https://images.pexels.com/photos/3731471/pexels-photo-3731471.jpeg',
    category: 'desayuno',
    accessLevel: 'free',
    prepTime: 5,
    cookTime: 10,
    nutrition: { calories: 280, protein: 26, carbs: 22, fat: 11 },
    tags: ['alto proteico', 'energia', 'rapido', 'sin lactosa'],
    isFeatured: false,
    ingredients: [
      { name: 'claras de huevo', amount: '3', unit: 'unidades' },
      { name: 'huevo entero', amount: '1', unit: 'unidad' },
      { name: 'espinaca picada', amount: '1/2', unit: 'taza' },
      { name: 'champiñones en láminas', amount: '1/4', unit: 'taza' },
      { name: 'cebolla picada', amount: '1/4', unit: 'unidad' },
      { name: 'pan integral', amount: '1', unit: 'rebanada' },
      { name: 'aceite de oliva', amount: '5', unit: 'ml' },
      { name: 'sal y pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Saltear cebolla y champiñones con el aceite de oliva.',
      'Añadir la espinaca y cocinar 1–2 minutos.',
      'Batir claras y huevo con sal y pimienta, verter sobre las verduras y cocinar hasta que cuaje tipo omelette.',
      'Servir con la tostada integral al lado.',
    ],
  },
  {
    name: 'Snack mañana – Yogur griego con semillas',
    description: 'Snack de media mañana rico en proteína, omega-3 y fibra. Las semillas de chía y linaza potencian la saciedad y el equilibrio hormonal.',
    imageUrl: 'https://images.pexels.com/photos/4144224/pexels-photo-4144224.jpeg',
    category: 'snack',
    accessLevel: 'free',
    prepTime: 3,
    cookTime: 0,
    nutrition: { calories: 150, protein: 15, carbs: 7, fat: 6 },
    tags: ['alto proteico', 'omega 3', 'fibra', 'sin coccion', 'probioticos'],
    isFeatured: false,
    ingredients: [
      { name: 'yogur griego light', amount: '150', unit: 'g' },
      { name: 'semillas de chía', amount: '5', unit: 'g' },
      { name: 'semillas de linaza molida', amount: '5', unit: 'g' },
      { name: 'stevia o gotas de vainilla', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Colocar el yogur en un bowl.',
      'Añadir chía y linaza por encima.',
      'Endulzar con stevia o saborizar con vainilla.',
      'Mezclar y servir frío.',
    ],
  },
  {
    name: 'Almuerzo – Ensalada ligera de pollo',
    description: 'Almuerzo fresco, saciante y bajo en carbohidratos. Proteína magra de pollo con vegetales crujientes, ideal para días de definición.',
    imageUrl: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg',
    category: 'almuerzo',
    accessLevel: 'free',
    prepTime: 10,
    cookTime: 0,
    nutrition: { calories: 340, protein: 33, carbs: 10, fat: 19 },
    tags: ['alto proteico', 'bajo carbos', 'sin gluten', 'keto', 'definicion'],
    isFeatured: false,
    ingredients: [
      { name: 'pechuga de pollo a la plancha en tiras', amount: '120', unit: 'g' },
      { name: 'mezcla de lechugas', amount: '2', unit: 'tazas' },
      { name: 'pepino en rodajas', amount: '1/2', unit: 'taza' },
      { name: 'tomate cherry', amount: '1/2', unit: 'taza' },
      { name: 'cebolla morada', amount: '1/4', unit: 'unidad' },
      { name: 'aceite de oliva', amount: '10', unit: 'ml' },
      { name: 'limón (jugo)', amount: '1/2', unit: 'unidad' },
      { name: 'sal y pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Colocar las lechugas en un bowl.',
      'Añadir pepino, tomate y cebolla.',
      'Agregar el pollo en tiras.',
      'Aliñar con aceite de oliva, limón, sal y pimienta y mezclar bien.',
    ],
  },
  {
    name: 'Snack tarde – Zanahoria con hummus',
    description: 'Snack de tarde crujiente y nutritivo. Fibra de la zanahoria + proteína vegetal del hummus para controlar el hambre sin sumar calorías vacías.',
    imageUrl: 'https://images.pexels.com/photos/3730951/pexels-photo-3730951.jpeg',
    category: 'snack',
    accessLevel: 'free',
    prepTime: 3,
    cookTime: 0,
    nutrition: { calories: 140, protein: 4, carbs: 14, fat: 7 },
    tags: ['vegano', 'sin coccion', 'fibra', 'rapido', 'sin gluten'],
    isFeatured: false,
    ingredients: [
      { name: 'zanahoria en bastones', amount: '80', unit: 'g' },
      { name: 'hummus clásico', amount: '40', unit: 'g' },
    ],
    steps: [
      'Lavar y cortar la zanahoria en bastones.',
      'Servir el hummus en un recipiente pequeño.',
      'Acompañar los bastones de zanahoria con el hummus como dip.',
    ],
  },
  {
    name: 'Cena – Tacos de lechuga con pavo',
    description: 'Cena ligera y sabrosa sin carbohidratos pesados. La lechuga reemplaza la tortilla para una opción baja en calorías con toda la proteína del pavo.',
    imageUrl: 'https://images.pexels.com/photos/6546027/pexels-photo-6546027.jpeg',
    category: 'cena',
    accessLevel: 'basic',
    prepTime: 5,
    cookTime: 10,
    nutrition: { calories: 260, protein: 28, carbs: 8, fat: 11 },
    tags: ['alto proteico', 'bajo carbos', 'sin gluten', 'keto', 'rapido'],
    isFeatured: false,
    ingredients: [
      { name: 'pechuga de pavo molida o picada', amount: '100', unit: 'g' },
      { name: 'hojas grandes de lechuga', amount: '4', unit: 'unidades' },
      { name: 'cebolla picada', amount: '1/4', unit: 'taza' },
      { name: 'tomate picado', amount: '1/4', unit: 'taza' },
      { name: 'pimentón', amount: '1/4', unit: 'taza' },
      { name: 'aceite de oliva', amount: '5', unit: 'ml' },
      { name: 'sal, pimienta, comino y paprika', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Saltear la cebolla y el pimentón con aceite de oliva.',
      'Añadir el pavo y cocinar hasta que esté dorado.',
      'Sazonar con sal, pimienta, comino y paprika.',
      'Rellenar las hojas de lechuga con la mezcla de pavo y el tomate picado.',
    ],
  },
  {
    name: 'Post-entreno – Shake proteína pérdida de grasa',
    description: 'Batido post entreno diseñado para recuperación muscular y pérdida de grasa. Proteína de rápida absorción con carbohidratos de avena y banana para reponer glucógeno.',
    imageUrl: 'https://images.pexels.com/photos/1438084/pexels-photo-1438084.jpeg',
    category: 'batido',
    accessLevel: 'basic',
    prepTime: 5,
    cookTime: 0,
    nutrition: { calories: 280, protein: 25, carbs: 35, fat: 4 },
    tags: ['post entreno', 'alto proteico', 'recuperacion', 'perdida de grasa'],
    isFeatured: false,
    ingredients: [
      { name: 'agua o bebida vegetal sin azúcar', amount: '200', unit: 'ml' },
      { name: 'proteína en polvo', amount: '1', unit: 'scoop (20–25g)' },
      { name: 'avena', amount: '30', unit: 'g' },
      { name: 'banana pequeña', amount: '1/2', unit: 'unidad' },
      { name: 'hielo', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Colocar agua, proteína, avena y banana en la licuadora.',
      'Añadir hielo.',
      'Licuar hasta que quede homogéneo.',
      'Tomar justo después de entrenar.',
    ],
  },

  // ========== DÍA 2 — COLA/PIERNAS ==========
  {
    name: 'D2 – Desayuno avena para glúteos',
    description: 'Avena caliente con banana, mantequilla de maní y chía. Cargada de carbohidratos de calidad para maximizar el rendimiento en el entrenamiento de cola y piernas.',
    imageUrl: 'https://images.pexels.com/photos/3731520/pexels-photo-3731520.jpeg',
    category: 'desayuno',
    accessLevel: 'free',
    prepTime: 2,
    cookTime: 8,
    nutrition: { calories: 480, protein: 18, carbs: 68, fat: 14 },
    tags: ['gluteos', 'energia', 'carbohidratos', 'pre entreno', 'dia 2'],
    isFeatured: false,
    ingredients: [
      { name: 'avena', amount: '60', unit: 'g' },
      { name: 'leche o bebida vegetal', amount: '200', unit: 'ml' },
      { name: 'banana en rodajas', amount: '1', unit: 'unidad' },
      { name: 'mantequilla de maní', amount: '15', unit: 'g' },
      { name: 'semillas de chía', amount: '10', unit: 'g' },
      { name: 'canela', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'En una olla, mezclar avena y leche.',
      'Cocinar a fuego medio hasta que espese.',
      'Retirar del fuego y agregar la banana, la mantequilla de maní y las semillas de chía.',
      'Espolvorear canela y servir.',
    ],
  },
  {
    name: 'D2 – Snack post entreno yogur proteico con fruta',
    description: 'Snack post-entreno pensado para la recuperación muscular de glúteos y piernas. 200g de yogur griego con fruta fresca para reponer glucógeno y aminoácidos.',
    imageUrl: 'https://images.pexels.com/photos/4144202/pexels-photo-4144202.jpeg',
    category: 'snack',
    accessLevel: 'basic',
    prepTime: 3,
    cookTime: 0,
    nutrition: { calories: 210, protein: 20, carbs: 24, fat: 4 },
    tags: ['post entreno', 'alto proteico', 'recuperacion', 'gluteos', 'dia 2'],
    isFeatured: false,
    ingredients: [
      { name: 'yogur griego natural alto en proteína', amount: '200', unit: 'g' },
      { name: 'frutos rojos o manzana en cubos', amount: '1/2', unit: 'taza' },
      { name: 'miel o stevia', amount: '5', unit: 'g' },
    ],
    steps: [
      'Colocar el yogur en un bowl.',
      'Añadir la fruta por encima.',
      'Endulzar ligeramente con miel o stevia.',
      'Consumir dentro de los 60 minutos posteriores al entreno.',
    ],
  },
  {
    name: 'D2 – Batido noche recuperación',
    description: 'Batido suave para tomar 1–2 horas antes de dormir en días de entrenamiento intenso. Favorece la recuperación muscular nocturna sin sobrecargar la digestión.',
    imageUrl: 'https://images.pexels.com/photos/5938241/pexels-photo-5938241.jpeg',
    category: 'batido',
    accessLevel: 'premium',
    prepTime: 5,
    cookTime: 0,
    nutrition: { calories: 180, protein: 6, carbs: 28, fat: 6 },
    tags: ['nocturno', 'recuperacion', 'omega 3', 'gluteos', 'dia 2'],
    isFeatured: false,
    ingredients: [
      { name: 'bebida vegetal sin azúcar', amount: '200', unit: 'ml' },
      { name: 'banana pequeña', amount: '1/2', unit: 'unidad' },
      { name: 'avena', amount: '10', unit: 'g' },
      { name: 'semillas de lino o chía', amount: '10', unit: 'g' },
      { name: 'canela', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Agregar bebida vegetal, banana, avena y semillas a la licuadora.',
      'Licuar hasta que quede suave.',
      'Añadir canela al gusto.',
      'Tomar 1–2 horas antes de dormir si el día de entreno fue intenso.',
    ],
  },

  // ========== DÍA 3 — PIEL RADIANTE Y OJERAS ==========
  {
    name: 'D3 – Snack frutos rojos y nueces',
    description: 'Snack antioxidante de media mañana con frutos rojos ricos en vitamina C y nueces con omega-3. Combate las ojeras y nutre la piel desde adentro.',
    imageUrl: 'https://images.pexels.com/photos/1435747/pexels-photo-1435747.jpeg',
    category: 'snack',
    accessLevel: 'free',
    prepTime: 3,
    cookTime: 0,
    nutrition: { calories: 150, protein: 3, carbs: 18, fat: 8 },
    tags: ['antioxidante', 'piel', 'omega 3', 'sin coccion', 'dia 3'],
    isFeatured: false,
    ingredients: [
      { name: 'frutos rojos (fresas, arándanos, moras)', amount: '80', unit: 'g' },
      { name: 'nueces picadas', amount: '10', unit: 'g' },
    ],
    steps: [
      'Lavar bien los frutos rojos.',
      'Servir en un bowl.',
      'Añadir las nueces picadas por encima.',
      'Consumir a media mañana.',
    ],
  },
  {
    name: 'D3 – Almuerzo ensalada salmón y aguacate',
    description: 'Almuerzo antiinflamatorio con salmón rico en omega-3 y aguacate lleno de grasas saludables. Perfecto para reducir ojeras, mejorar la piel y cuidar las articulaciones.',
    imageUrl: 'https://images.pexels.com/photos/3296273/pexels-photo-3296273.jpeg',
    category: 'almuerzo',
    accessLevel: 'basic',
    prepTime: 10,
    cookTime: 10,
    nutrition: { calories: 480, protein: 30, carbs: 14, fat: 32 },
    tags: ['omega 3', 'antiinflamatorio', 'piel', 'ojeras', 'dia 3'],
    isFeatured: true,
    ingredients: [
      { name: 'salmón a la plancha', amount: '100', unit: 'g' },
      { name: 'mezcla de hojas verdes', amount: '2', unit: 'tazas' },
      { name: 'aguacate en láminas', amount: '1/4', unit: 'unidad' },
      { name: 'pepino en rodajas', amount: '1/2', unit: 'taza' },
      { name: 'tomate cherry', amount: '1/2', unit: 'taza' },
      { name: 'aceite de oliva', amount: '10', unit: 'ml' },
      { name: 'limón (jugo)', amount: '1/2', unit: 'unidad' },
      { name: 'sal y pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Colocar las hojas verdes en un plato.',
      'Añadir pepino, tomate y aguacate.',
      'Incorporar el salmón desmenuzado.',
      'Aliñar con aceite de oliva, limón, sal y pimienta.',
    ],
  },
  {
    name: 'D3 – Cena crema de calabaza y zanahoria',
    description: 'Cena reconfortante y antiinflamatoria con betacarotenos de calabaza y zanahoria. Favorece la regeneración de la piel, reduce la inflamación y es fácil de digerir.',
    imageUrl: 'https://images.pexels.com/photos/4109998/pexels-photo-4109998.jpeg',
    category: 'cena',
    accessLevel: 'premium',
    prepTime: 10,
    cookTime: 25,
    nutrition: { calories: 190, protein: 4, carbs: 32, fat: 6 },
    tags: ['antiinflamatorio', 'piel', 'betacarotenos', 'vegano', 'sin gluten', 'dia 3'],
    isFeatured: true,
    ingredients: [
      { name: 'calabaza (ahuyama) en cubos', amount: '150', unit: 'g' },
      { name: 'zanahoria en rodajas', amount: '80', unit: 'g' },
      { name: 'cebolla', amount: '1/4', unit: 'unidad' },
      { name: 'ajo', amount: '1', unit: 'diente' },
      { name: 'aceite de oliva', amount: '5', unit: 'ml' },
      { name: 'caldo de verduras', amount: '300', unit: 'ml' },
      { name: 'sal, pimienta y cúrcuma', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Saltear cebolla y ajo con el aceite de oliva.',
      'Añadir calabaza y zanahoria, mezclar.',
      'Agregar caldo, sal, pimienta y cúrcuma, cocinar hasta que estén tiernas.',
      'Licuar todo hasta obtener crema suave y servir caliente.',
    ],
  },

  // ========== DÍA 4 — PÉRDIDA DE PESO + SACIEDAD ==========
  {
    name: 'D4 – Desayuno bowl avena y manzana',
    description: 'Desayuno bajo en calorías y alto en fibra con avena y manzana. La chía aporta saciedad durante horas, ideal para un día enfocado en pérdida de grasa sin hambre.',
    imageUrl: 'https://images.pexels.com/photos/3731474/pexels-photo-3731474.jpeg',
    category: 'desayuno',
    accessLevel: 'free',
    prepTime: 2,
    cookTime: 7,
    nutrition: { calories: 230, protein: 7, carbs: 40, fat: 4 },
    tags: ['bajo calorias', 'fibra alta', 'saciedad', 'perdida de peso', 'dia 4'],
    isFeatured: false,
    ingredients: [
      { name: 'avena', amount: '40', unit: 'g' },
      { name: 'agua o leche baja en grasa', amount: '200', unit: 'ml' },
      { name: 'manzana en cubos', amount: '1/2', unit: 'unidad' },
      { name: 'semillas de chía', amount: '5', unit: 'g' },
      { name: 'canela', amount: 'al gusto', unit: '' },
      { name: 'stevia', amount: 'opcional', unit: '' },
    ],
    steps: [
      'Cocinar la avena con el agua o leche hasta que espese.',
      'Añadir la manzana en cubos y la chía.',
      'Espolvorear canela y endulzar con stevia si se desea.',
      'Servir caliente.',
    ],
  },
  {
    name: 'D4 – Snack mañana manzana con almendras',
    description: 'Snack de saciedad con la combinación perfecta de fibra de la manzana y grasas saludables de las almendras. Controla el hambre sin sumar calorías vacías.',
    imageUrl: 'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg',
    category: 'snack',
    accessLevel: 'free',
    prepTime: 2,
    cookTime: 0,
    nutrition: { calories: 160, protein: 3, carbs: 22, fat: 7 },
    tags: ['fibra alta', 'saciedad', 'perdida de peso', 'sin coccion', 'dia 4'],
    isFeatured: false,
    ingredients: [
      { name: 'manzana pequeña', amount: '1', unit: 'unidad' },
      { name: 'almendras naturales', amount: '10', unit: 'g' },
    ],
    steps: [
      'Lavar y cortar la manzana en gajos.',
      'Servir junto con las almendras.',
      'Consumir a media mañana.',
    ],
  },
  {
    name: 'D4 – Snack tarde yogur light con frutos rojos',
    description: 'Snack de tarde bajo en calorías con proteína del yogur griego y antioxidantes de los frutos rojos. Saciante y refrescante para no picar entre comidas.',
    imageUrl: 'https://images.pexels.com/photos/4144202/pexels-photo-4144202.jpeg',
    category: 'snack',
    accessLevel: 'basic',
    prepTime: 3,
    cookTime: 0,
    nutrition: { calories: 130, protein: 13, carbs: 14, fat: 3 },
    tags: ['bajo calorias', 'alto proteico', 'antioxidante', 'sin coccion', 'dia 4'],
    isFeatured: false,
    ingredients: [
      { name: 'yogur griego light', amount: '150', unit: 'g' },
      { name: 'frutos rojos', amount: '50', unit: 'g' },
    ],
    steps: [
      'Colocar el yogur en un bowl.',
      'Añadir frutos rojos por encima.',
      'Mezclar ligeramente y servir frío.',
    ],
  },
  {
    name: 'D4 – Cena sopa de verduras y pollo',
    description: 'Cena caliente, saciante y muy baja en calorías. Proteína de pollo con caldo de verduras, perfecta para un día de restricción calórica sin pasar hambre.',
    imageUrl: 'https://images.pexels.com/photos/6287521/pexels-photo-6287521.jpeg',
    category: 'cena',
    accessLevel: 'premium',
    prepTime: 10,
    cookTime: 20,
    nutrition: { calories: 260, protein: 26, carbs: 16, fat: 9 },
    tags: ['bajo calorias', 'alto proteico', 'saciedad', 'sin gluten', 'dia 4'],
    isFeatured: false,
    ingredients: [
      { name: 'pechuga de pollo en cubos', amount: '80', unit: 'g' },
      { name: 'zanahoria en cubos', amount: '1/2', unit: 'taza' },
      { name: 'calabacín en cubos', amount: '1/2', unit: 'taza' },
      { name: 'apio picado', amount: '1/4', unit: 'taza' },
      { name: 'cebolla', amount: '1/4', unit: 'unidad' },
      { name: 'caldo de pollo bajo en grasa', amount: '400', unit: 'ml' },
      { name: 'sal, pimienta y perejil', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Saltear cebolla y apio en una olla.',
      'Añadir zanahoria, calabacín y pollo, mezclar.',
      'Agregar caldo, sal y pimienta y cocinar hasta que el pollo esté listo.',
      'Servir con perejil picado por encima.',
    ],
  },

  // ========== DÍA 5 — GLÚTEOS HEAVY ==========
  {
    name: 'D5 – Snack pre entreno tostada con plátano',
    description: 'Pre-entreno cargado de carbohidratos de liberación sostenida. La combinación de pan integral, banana y maní te da energía constante para un entrenamiento heavy de glúteos.',
    imageUrl: 'https://images.pexels.com/photos/4198014/pexels-photo-4198014.jpeg',
    category: 'snack',
    accessLevel: 'free',
    prepTime: 3,
    cookTime: 2,
    nutrition: { calories: 230, protein: 7, carbs: 30, fat: 9 },
    tags: ['pre entreno', 'gluteos', 'carbohidratos', 'energia', 'dia 5'],
    isFeatured: false,
    ingredients: [
      { name: 'pan integral', amount: '1', unit: 'rebanada' },
      { name: 'banana en rodajas', amount: '1/2', unit: 'unidad' },
      { name: 'mantequilla de maní', amount: '10', unit: 'g' },
    ],
    steps: [
      'Tostar el pan integral.',
      'Untar la mantequilla de maní.',
      'Colocar las rodajas de banana encima.',
      'Consumir 45–60 min antes del entreno.',
    ],
  },

  // ========== DÍA 6 — PIEL Y BIENESTAR ==========
  {
    name: 'D6 – Desayuno yogur piel radiante',
    description: 'Desayuno fresco y nutritivo para cuidar la piel desde adentro. El yogur griego aporta proteína y probióticos, los frutos rojos antioxidantes y las nueces omega-3.',
    imageUrl: 'https://images.pexels.com/photos/1435747/pexels-photo-1435747.jpeg',
    category: 'desayuno',
    accessLevel: 'free',
    prepTime: 5,
    cookTime: 0,
    nutrition: { calories: 280, protein: 20, carbs: 25, fat: 10 },
    tags: ['piel', 'antioxidante', 'probioticos', 'sin coccion', 'dia 6'],
    isFeatured: true,
    ingredients: [
      { name: 'yogur griego natural', amount: '200', unit: 'g' },
      { name: 'frutos rojos', amount: '50', unit: 'g' },
      { name: 'semillas de chía', amount: '5', unit: 'g' },
      { name: 'nueces picadas', amount: '5', unit: 'g' },
      { name: 'miel', amount: '5', unit: 'g' },
    ],
    steps: [
      'Colocar el yogur en un bowl.',
      'Añadir frutos rojos, chía y nueces.',
      'Endulzar con miel y mezclar.',
    ],
  },
  {
    name: 'D6 – Snack mañana zanahoria y pepino',
    description: 'Snack hidratante y bajo en calorías con zanahoria y pepino. Rico en betacarotenos y agua para nutrir e hidratar la piel desde la mañana.',
    imageUrl: 'https://images.pexels.com/photos/4113805/pexels-photo-4113805.jpeg',
    category: 'snack',
    accessLevel: 'free',
    prepTime: 3,
    cookTime: 0,
    nutrition: { calories: 60, protein: 2, carbs: 12, fat: 0 },
    tags: ['hidratante', 'piel', 'bajo calorias', 'vegano', 'sin coccion', 'dia 6'],
    isFeatured: false,
    ingredients: [
      { name: 'zanahoria en bastones', amount: '60', unit: 'g' },
      { name: 'pepino en bastones', amount: '60', unit: 'g' },
      { name: 'limón (jugo)', amount: '10', unit: 'ml' },
      { name: 'sal ligera', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Cortar zanahoria y pepino en bastones.',
      'Rociar con limón.',
      'Agregar una pizca de sal.',
      'Mezclar y comer fresco.',
    ],
  },
  {
    name: 'D6 – Snack tarde té verde con limón y fruta',
    description: 'Bebida antioxidante con té verde, rico en catequinas para la piel y el metabolismo. Se acompaña de fruta fresca para completar los micronutrientes del día.',
    imageUrl: 'https://images.pexels.com/photos/4041020/pexels-photo-4041020.jpeg',
    category: 'bebida',
    accessLevel: 'basic',
    prepTime: 5,
    cookTime: 0,
    nutrition: { calories: 60, protein: 1, carbs: 15, fat: 0 },
    tags: ['antioxidante', 'piel', 'metabolismo', 'sin azucar', 'dia 6'],
    isFeatured: false,
    ingredients: [
      { name: 'té verde', amount: '1', unit: 'taza' },
      { name: 'limón (jugo)', amount: '1/4', unit: 'unidad' },
      { name: 'mandarina o kiwi', amount: '1', unit: 'unidad' },
    ],
    steps: [
      'Preparar el té verde.',
      'Agregar el jugo de limón y mezclar.',
      'Acompañar con la fruta elegida.',
    ],
  },
  {
    name: 'D6 – Cena ensalada de atún y aguacate',
    description: 'Cena ligera con proteína de atún, grasas saludables del aguacate y vegetales crudos. Baja en carbos, antiinflamatoria y fácil de preparar en minutos.',
    imageUrl: 'https://images.pexels.com/photos/4106480/pexels-photo-4106480.jpeg',
    category: 'cena',
    accessLevel: 'premium',
    prepTime: 8,
    cookTime: 0,
    nutrition: { calories: 320, protein: 23, carbs: 10, fat: 20 },
    tags: ['omega 3', 'alto proteico', 'bajo carbos', 'sin coccion', 'piel', 'dia 6'],
    isFeatured: false,
    ingredients: [
      { name: 'atún en agua escurrido', amount: '80', unit: 'g' },
      { name: 'aguacate en cubos', amount: '1/4', unit: 'unidad' },
      { name: 'lechuga', amount: '1', unit: 'taza' },
      { name: 'cebolla morada', amount: '1/4', unit: 'taza' },
      { name: 'tomate', amount: '1/4', unit: 'taza' },
      { name: 'aceite de oliva', amount: '10', unit: 'ml' },
      { name: 'limón (jugo)', amount: 'al gusto', unit: '' },
      { name: 'sal y pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Colocar lechuga en un bowl.',
      'Añadir atún, aguacate, cebolla y tomate.',
      'Aliñar con aceite, limón, sal y pimienta.',
      'Mezclar y servir.',
    ],
  },

  // ========== DÍA 7 — MIX EQUILIBRADO ==========
  {
    name: 'D7 – Desayuno bowl mexicano saludable',
    description: 'Desayuno completo estilo bowl mexicano con huevo, frijoles, aguacate y vegetales. Alto en proteína, fibra y grasas saludables para empezar el día con todo.',
    imageUrl: 'https://images.pexels.com/photos/4958654/pexels-photo-4958654.jpeg',
    category: 'desayuno',
    accessLevel: 'free',
    prepTime: 5,
    cookTime: 8,
    nutrition: { calories: 380, protein: 26, carbs: 24, fat: 19 },
    tags: ['alto proteico', 'fibra alta', 'grasas saludables', 'equilibrado', 'dia 7'],
    isFeatured: true,
    ingredients: [
      { name: 'huevos', amount: '2', unit: 'unidades' },
      { name: 'clara de huevo', amount: '1', unit: 'unidad' },
      { name: 'frijoles negros cocidos', amount: '40', unit: 'g' },
      { name: 'aguacate', amount: '1/4', unit: 'unidad' },
      { name: 'tomate picado', amount: '1/4', unit: 'taza' },
      { name: 'cebolla', amount: '1/4', unit: 'taza' },
      { name: 'cilantro', amount: 'al gusto', unit: '' },
      { name: 'tortilla integral pequeña (opcional)', amount: '1', unit: 'unidad' },
    ],
    steps: [
      'Revolver huevos y clara y cocinar en sartén.',
      'Calentar los frijoles.',
      'En un bowl colocar huevos, frijoles, tomate, cebolla y aguacate.',
      'Decorar con cilantro; opcional acompañar con tortilla.',
    ],
  },
  {
    name: 'D7 – Snack mañana yogur con fruta pequeña',
    description: 'Snack ligero y equilibrado con yogur griego y fruta fresca. Fácil, rápido y con la proteína justa para mantenerse activa entre el desayuno y el almuerzo.',
    imageUrl: 'https://images.pexels.com/photos/4144224/pexels-photo-4144224.jpeg',
    category: 'snack',
    accessLevel: 'free',
    prepTime: 2,
    cookTime: 0,
    nutrition: { calories: 110, protein: 9, carbs: 14, fat: 3 },
    tags: ['equilibrado', 'probioticos', 'rapido', 'sin coccion', 'dia 7'],
    isFeatured: false,
    ingredients: [
      { name: 'yogur griego natural', amount: '100', unit: 'g' },
      { name: 'manzana pequeña o mandarina', amount: '1/2', unit: 'unidad' },
    ],
    steps: [
      'Servir el yogur en un bowl.',
      'Añadir la fruta en trozos.',
      'Mezclar y consumir.',
    ],
  },
  {
    name: 'D7 – Almuerzo ensalada de lentejas y pollo',
    description: 'Ensalada completa que combina proteína vegetal de las lentejas con proteína animal del pollo. Alta en fibra, hierro y aminoácidos esenciales para el día de mix.',
    imageUrl: 'https://images.pexels.com/photos/1435895/pexels-photo-1435895.jpeg',
    category: 'almuerzo',
    accessLevel: 'basic',
    prepTime: 10,
    cookTime: 0,
    nutrition: { calories: 390, protein: 30, carbs: 35, fat: 13 },
    tags: ['alto proteico', 'fibra alta', 'hierro', 'equilibrado', 'dia 7'],
    isFeatured: false,
    ingredients: [
      { name: 'lentejas cocidas', amount: '80', unit: 'g' },
      { name: 'pechuga de pollo a la plancha en cubos', amount: '80', unit: 'g' },
      { name: 'pepino', amount: '1/2', unit: 'taza' },
      { name: 'tomate', amount: '1/2', unit: 'taza' },
      { name: 'cebolla morada', amount: '1/4', unit: 'unidad' },
      { name: 'aceite de oliva', amount: '10', unit: 'ml' },
      { name: 'limón (jugo)', amount: 'al gusto', unit: '' },
      { name: 'sal y pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Mezclar lentejas, pollo, pepino, tomate y cebolla.',
      'Aliñar con aceite, limón, sal y pimienta.',
      'Mezclar y servir frío.',
    ],
  },
  {
    name: 'D7 – Snack tarde frutos secos',
    description: 'Porción controlada de frutos secos, la fuente perfecta de grasas saludables, magnesio y vitamina E. Saciante y antiinflamatorio para la tarde.',
    imageUrl: 'https://images.pexels.com/photos/4110540/pexels-photo-4110540.jpeg',
    category: 'snack',
    accessLevel: 'basic',
    prepTime: 1,
    cookTime: 0,
    nutrition: { calories: 90, protein: 3, carbs: 3, fat: 8 },
    tags: ['grasas saludables', 'magnesio', 'equilibrado', 'sin coccion', 'dia 7'],
    isFeatured: false,
    ingredients: [
      { name: 'mix de frutos secos (almendras, nueces, anacardos)', amount: '15', unit: 'g' },
    ],
    steps: [
      'Pesar la porción de frutos secos (15g).',
      'Consumir como snack a media tarde.',
    ],
  },
  {
    name: 'D7 – Cena bowl ligero verduras y huevo',
    description: 'Cena ligera y completa para cerrar la semana con equilibrio. Proteína del huevo con verduras salteadas, baja en carbos y reconfortante.',
    imageUrl: 'https://images.pexels.com/photos/3731471/pexels-photo-3731471.jpeg',
    category: 'cena',
    accessLevel: 'premium',
    prepTime: 5,
    cookTime: 8,
    nutrition: { calories: 280, protein: 26, carbs: 8, fat: 16 },
    tags: ['alto proteico', 'bajo carbos', 'equilibrado', 'sin gluten', 'dia 7'],
    isFeatured: false,
    ingredients: [
      { name: 'huevos', amount: '2', unit: 'unidades' },
      { name: 'claras de huevo', amount: '2', unit: 'unidades' },
      { name: 'verduras salteadas (brócoli, pimentón, calabacín)', amount: '1', unit: 'taza' },
      { name: 'aceite de oliva', amount: '5', unit: 'ml' },
      { name: 'sal, pimienta y especias', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Saltear las verduras con aceite de oliva.',
      'Batir huevos y claras con sal y pimienta.',
      'Verter sobre las verduras y cocinar revuelto.',
      'Servir en bowl.',
    ],
  },

  {
    name: 'Cena de salmón y quinoa para glúteos',
    description: 'Cena premium diseñada para la recuperación nocturna y el crecimiento de glúteos. Omega-3 del salmón + proteína completa de la quinoa = resultados visibles.',
    imageUrl: 'https://images.pexels.com/photos/3296273/pexels-photo-3296273.jpeg',
    category: 'cena',
    accessLevel: 'premium',
    prepTime: 5,
    cookTime: 20,
    nutrition: { calories: 560, protein: 38, carbs: 35, fat: 24 },
    tags: ['omega 3', 'alto proteico', 'gluteos', 'antiinflamatorio', 'sin gluten'],
    isFeatured: true,
    ingredients: [
      { name: 'filete de salmón a la plancha', amount: '120', unit: 'g' },
      { name: 'quinoa cocida', amount: '60', unit: 'g' },
      { name: 'espárragos o brócoli al vapor', amount: '1', unit: 'taza' },
      { name: 'aceite de oliva', amount: '10', unit: 'ml' },
      { name: 'limón (jugo)', amount: 'al gusto', unit: '' },
      { name: 'sal y pimienta', amount: 'al gusto', unit: '' },
    ],
    steps: [
      'Cocinar la quinoa según indicaciones del empaque.',
      'Hacer el salmón a la plancha con sal, pimienta y limón.',
      'Cocinar los espárragos o brócoli al vapor.',
      'Servir salmón, quinoa y verduras, y terminar con aceite de oliva y limón.',
    ],
  },
];

async function seedRecipes() {
  try {
    await connectDB();
    console.log('\n🌱 Iniciando seed de recetas...\n');

    // Eliminar recetas existentes
    const deleted = await Recipe.deleteMany({});
    console.log(`🗑️  ${deleted.deletedCount} recetas anteriores eliminadas`);

    // Insertar nuevas recetas
    const inserted = await Recipe.insertMany(recipes);
    console.log(`✅ ${inserted.length} recetas insertadas:\n`);

    inserted.forEach((r) => {
      const lock = r.accessLevel === 'free' ? '🆓' : r.accessLevel === 'basic' ? '🔵' : '⭐';
      console.log(`  ${lock} [${r.category}] ${r.name}`);
    });

    console.log('\n✨ Seed completado exitosamente\n');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error en seed:', error);
    process.exit(1);
  }
}

seedRecipes();
